"""added rpi table

Revision ID: 12b0956b6db0
Revises: adc8a2e6eb25
Create Date: 2023-02-24 23:09:48.557524+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12b0956b6db0'
down_revision = 'adc8a2e6eb25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rpi',
    sa.Column('rpi_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=100), nullable=False),
    sa.Column('rpi_ip', postgresql.INET(), nullable=False),
    sa.Column('rpi_mac', postgresql.MACADDR(), nullable=False),
    sa.Column('rpi_v', sa.String(length=255), nullable=False),
    sa.Column('os_v', sa.String(length=255), nullable=False),
    sa.Column('memory', sa.BigInteger(), nullable=False),
    sa.Column('storage_cap', sa.BigInteger(), nullable=False),
    sa.Column('cpu_type', sa.String(length=255), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('op_status', sa.Boolean(), nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.hardware_id'], ),
    sa.PrimaryKeyConstraint('rpi_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpi')
    # ### end Alembic commands ###
