"""set all foreign keys to not nullable

Revision ID: 278b4561409b
Revises: 84dde0cf3238
Create Date: 2023-02-27 23:50:40.878673+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278b4561409b'
down_revision = '84dde0cf3238'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hardware', 'mount_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('outputs', 'recording_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recordings', 'hardware_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('recordings', 'metadata_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rpi', 'hardware_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sdr', 'hardware_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('status', 'hardware_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('wrlen', 'hardware_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wrlen', 'hardware_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('status', 'hardware_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sdr', 'hardware_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rpi', 'hardware_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recordings', 'metadata_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('recordings', 'hardware_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('outputs', 'recording_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('hardware', 'mount_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
