"""empty message

Revision ID: 33ae53e964bb
Revises: 755f4357d8bb
Create Date: 2023-07-13 21:31:31.272099+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33ae53e964bb'
down_revision = '755f4357d8bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outputs', 'output_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outputs', sa.Column('output_path', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
