"""added recordings table

Revision ID: 386d51413d4c
Revises: 9b5dab693995
Create Date: 2023-02-23 22:39:43.522046+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386d51413d4c'
down_revision = '9b5dab693995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
    sa.Column('recording_id', sa.BigInteger(), nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.Column('metadata_id', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('survey_id', sa.CHAR(length=6), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('entered_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.hardware_id'], ),
    sa.ForeignKeyConstraint(['metadata_id'], ['metadata.metadata_id'], ),
    sa.PrimaryKeyConstraint('recording_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recordings')
    # ### end Alembic commands ###
