"""added sdr table

Revision ID: 4c8e327c0ffe
Revises: 12b0956b6db0
Create Date: 2023-02-25 00:00:15.325130+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c8e327c0ffe'
down_revision = '12b0956b6db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sdr',
    sa.Column('sdr_id', sa.Integer(), nullable=False),
    sa.Column('sdr_serial', sa.CHAR(), nullable=False),
    sa.Column('mboard_name', sa.String(length=255), nullable=False),
    sa.Column('external_clock', sa.Boolean(), nullable=False),
    sa.Column('op_status', sa.Boolean(), nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.hardware_id'], ),
    sa.PrimaryKeyConstraint('sdr_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sdr')
    # ### end Alembic commands ###
