"""introduced version file fixes

Revision ID: 7ebb4da99cee
Revises: 36d58c6bc5e4
Create Date: 2022-11-03 22:06:36.267082+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebb4da99cee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_table',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('wr_mac', sa.String(length=20), nullable=False),
    sa.Column('rpi_mac', sa.String(length=20), nullable=False),
    sa.Column('hostname', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alembic_version')
    # ### end Alembic commands ###
