"""added status table

Revision ID: 84dde0cf3238
Revises: ea48d8e63ac4
Create Date: 2023-02-27 23:38:11.098102+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84dde0cf3238'
down_revision = 'ea48d8e63ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('hostname', sa.String(length=50), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=False),
    sa.Column('rpi_cpu_temp', sa.Numeric(), nullable=False),
    sa.Column('sdr_temp', sa.Numeric(), nullable=False),
    sa.Column('avg_cpu_usage', sa.Numeric(), nullable=False),
    sa.Column('bytes_recorded', sa.BigInteger(), nullable=False),
    sa.Column('rem_nfs_storage_cap', sa.BigInteger(), nullable=False),
    sa.Column('rem_rpi_storage_cap', sa.BigInteger(), nullable=False),
    sa.Column('rpi_uptime_minutes', sa.BigInteger(), nullable=False),
    sa.Column('hardware_id', sa.Integer(), nullable=True),
    sa.Column('wr_servo_state', sa.String(length=50), nullable=False),
    sa.Column('wr_sfp1_link', sa.Boolean(), nullable=False),
    sa.Column('wr_sfp2_link', sa.Boolean(), nullable=False),
    sa.Column('wr_sfp1_tx', sa.BigInteger(), nullable=False),
    sa.Column('wr_sfp1_rx', sa.BigInteger(), nullable=False),
    sa.Column('wr_sfp2_tx', sa.BigInteger(), nullable=False),
    sa.Column('wr_sfp2_rx', sa.BigInteger(), nullable=False),
    sa.Column('wr_phase_setp', sa.Integer(), nullable=False),
    sa.Column('wr_rtt', sa.Integer(), nullable=False),
    sa.Column('wr_crtt', sa.Integer(), nullable=False),
    sa.Column('wr_clck_offset', sa.Boolean(), nullable=False),
    sa.Column('wr_updt_cnt', sa.Integer(), nullable=False),
    sa.Column('wr_temp', sa.Numeric(), nullable=False),
    sa.Column('wr_host', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.hardware_id'], ),
    sa.PrimaryKeyConstraint('status_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    # ### end Alembic commands ###
