"""added metadata table

Revision ID: 9b5dab693995
Revises: 1139d2e48396
Create Date: 2023-02-23 00:02:35.210233+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5dab693995'
down_revision = '1139d2e48396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata',
    sa.Column('metadata_id', sa.Integer(), nullable=False),
    sa.Column('org', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.BigInteger(), nullable=False),
    sa.Column('sample_rate', sa.BigInteger(), nullable=False),
    sa.Column('gain', sa.Integer(), nullable=False),
    sa.Column('length', sa.Numeric(), nullable=False),
    sa.Column('interval', sa.Numeric(), nullable=False),
    sa.Column('bit_depth', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('metadata_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata')
    # ### end Alembic commands ###
