"""added outputs table

Revision ID: adc8a2e6eb25
Revises: 9e44143567d6
Create Date: 2023-02-24 00:53:17.570668+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc8a2e6eb25'
down_revision = '9e44143567d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outputs',
    sa.Column('output_id', sa.BigInteger(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('average_db', sa.Numeric(precision=21, scale=16), nullable=False),
    sa.Column('max_db', sa.Numeric(precision=21, scale=16), nullable=False),
    sa.Column('median_db', sa.Numeric(precision=21, scale=16), nullable=False),
    sa.Column('std_dev', sa.Numeric(), nullable=False),
    sa.Column('kurtosis', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.recording_id'], ),
    sa.PrimaryKeyConstraint('output_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outputs')
    # ### end Alembic commands ###
