"""added nfs_mnt column to hardware_table

Revision ID: cc8cfc77a0a5
Revises: 7ebb4da99cee
Create Date: 2022-11-03 22:24:00.537135+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc8cfc77a0a5'
down_revision = '7ebb4da99cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hardware_table',
            sa.Column('nfs_mnt', mysql.VARCHAR(length=30), nullable=False)
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_table',
    sa.Column('id', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('wr_mac', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('rpi_mac', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('hostname', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('comment', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
