"""removed column cpu_usage from table status

Revision ID: ec9e96168d45
Revises: f5b8f2c4de3c
Create Date: 2023-01-19 22:53:42.893509+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec9e96168d45'
down_revision = 'f5b8f2c4de3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'cpu_usage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', Column('cpu_usage', Numeric()))
    # ### end Alembic commands ###
