"""initialize nrdz db

Revision ID: f5b8f2c4de3c
Revises: 
Create Date: 2023-01-18 01:05:24.293232+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5b8f2c4de3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('status_id', sa.String(length=20), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('rpi_cpu_temp', sa.Numeric(), nullable=True),
    sa.Column('cpu_usage', sa.Numeric(), nullable=True),
    sa.Column('avg_cpu_usage', sa.Numeric(), nullable=True),
    sa.Column('bytes_recorded', sa.BigInteger(), nullable=True),
    sa.Column('storage_cap', sa.Numeric(), nullable=True),
    sa.Column('hardware_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.hardware_id'], ),
    sa.PrimaryKeyConstraint('status_id', 'time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    # ### end Alembic commands ###
